CREATE TABLE IF NOT EXISTS LANGUAGE (
    ENTITY_ID IDENTITY PRIMARY KEY,
    NAME      VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS CLASSIFICATION (
    ENTITY_ID IDENTITY PRIMARY KEY,
    NAME      VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS DOCUMENT (
    ENTITY_ID         IDENTITY PRIMARY KEY,
    FULL_NAME         VARCHAR(133) NOT NULL,
    NAME              VARCHAR(128) NOT NULL,
    EXTENSION         VARCHAR(5) NOT NULL,
    CLASSIFICATION_ID BIGINT NOT NULL REFERENCES CLASSIFICATION(ENTITY_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DOCUMENT_LANGUAGE (
    ENTITY_ID   IDENTITY PRIMARY KEY,
    DOCUMENT_ID BIGINT NOT NULL REFERENCES DOCUMENT(ENTITY_ID) ON DELETE CASCADE,
    LANGUAGE_ID BIGINT NOT NULL REFERENCES LANGUAGE(ENTITY_ID) ON DELETE CASCADE,
    DATA        BYTEA NOT NULL
);