server:
  port: 8091

spring:
  profiles:
    active: dev

module-properties:
  persistence:
    url: jdbc:postgresql://localhost:5433/docs
    scheme: docs
    username: docs_appl
    password: qwe123
    maxPoolSize: 5