server:
  port: 8091

spring:
  servlet:
    multipart:
      max-file-size: 6MB

module-properties:
  auth:
    cookie:
      authCookieName: AUTH_TOKEN
      secret: ENC(2lC1bZryCBUnMXoe+0a2a6KdaeG2OTbdR9LhUM44gYyhmfwXcCfiUnEOu+m5nIRH)
  persistence:
    url: jdbc:postgresql://common-db:5432/docs
    schema: docs
    username: ENC(l8wHZB10C6nJdYTEj0kGqZOoo+ruL7HfuLrUNfC+GeSPaq+EimGJesD9YGS8ZuIa)
    password: ENC(Q25fdX5HGiXN/WsxWGXW3IE0ibpJ0r1T9y84f+z7ysz1Mn9/W3fn9pIQqohPv/Wn)
    maxPoolSize: 10

jasypt:
  encryptor:
    password: ${JASYPT-ENCRYPTOR-PWD}
    pool-size: 5